# Generated by Django 3.1.4 on 2021-04-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
